name: newSessionHosts_${{ parameters.ImageDefinitionName }}_${{ parameters.ImageDefinitionVersion }}_$(Build.BuildId)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: 'Import-AVD_NL.git'
      type: git
      name: 'Dev-AVD-NL/Import-AVD_NL.git'
      ref: 'refs/heads/main'

parameters:
  - name: Environment
    type: string
    values:
    - dev
    - tst
    - uat
    - prd
  - name: SNOWNumber
    displayName: ServiceNow Ticket Number
    type: string
    default: 'None'
  - name: ComputeGalleryName
    displayName: Azure Compute Gallery Name
    type: string
  - name: ImageDefinitionName
    displayName: Image Definition Name
    type: string
  - name: ImageDefinitionVersion
    displayName: Image Definition Version
    type: string
  - name: HostCount
    displayName: Number of hosts to deploy
    type: string
  - name: StartIndex
    displayName: Index to start from
    type: string
  - name: vmImageName
    type: string
    default: 'windows-latest'
  - name: ServiceConnectionName
    type: string
    default: 'AVD01'

variables:
  - group: avd-terraform-vars

stages:
  - stage: cav
    displayName: CaV | Collect Resources
    jobs:
      - job: A1
        displayName: A1 | Collect Required Resources
        pool:
          vmImage: ${{ parameters.vmImageName }}

        steps:
          - checkout: self
          - checkout: claranet-it

          - task: CopyFiles@2
            displayName: 'Task | Copy configuration files'
            inputs:
              SourceFolder: $(build.sourcesDirectory)/$(Build.Repository.Name)/configurations
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory)/configurations'
              CleanTargetFolder: false

          - task: CopyFiles@2
            displayName: 'Task | Copy template files'
            inputs:
              SourceFolder: $(build.sourcesDirectory)/Claranet-IT/templates
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory)/resources/templates'
              CleanTargetFolder: false
          
          - task: CopyFiles@2
            displayName: 'Task | Copy script files'
            inputs:
              SourceFolder: $(build.sourcesDirectory)/Claranet-IT/scripts
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory)/resources/scripts'
              CleanTargetFolder: false

          - publish: '$(System.ArtifactsDirectory)/configurations'
            displayName: Publishing CaV-1-configurations
            artifact: CaV-1-configurations

          - publish: '$(build.artifactstagingdirectory)/resources'
            displayName: Publishing CaV-1-resources
            artifact: CaV-1-resources