name: Terraform_State_Drift_Detection_${{ parameters.NlcNumber }}_$(Date:yyyyMMdd)-$(Build.BuildId)$(Rev:.r)

trigger: none

schedules:
- cron: '0 23 * * *'
  displayName: Daily Nightly Run
  branches:
    include:
    - main
    - master

resources:
  repositories:
    - repository: claranet-it
      type: git
      name: 'Claranet IT/Claranet-IT'
      ref: 'releases/v1.0.0'

parameters:
  - name: NlcNumber
    type: string
    default: 'NLC000883'
  - name: vmImageName
    type: string
    default: 'windows-latest'
  - name: ServiceConnectionName
    type: string
    default: 'nlc000883-schipper-prod-001'
  - name: Environment
    type: string
    values:
    - tst
    - dev
    - uat
    - prd
    default: prd

variables:
  - group: GVG_MANUAL_INFRA_AS_CODE_01

stages:
  - stage: cav
    displayName: CaV | Collect And Validate Resources
    jobs:
      - job: CAV1
        displayName: CaV1 | Collect And Validate Resources
        pool:
          vmImage: ${{ parameters.vmImageName }}

        steps:
          - checkout: self
          - checkout: claranet-it

          - task: CopyFiles@2
            displayName: 'Task | Copy template files '
            inputs:
              SourceFolder: $(build.sourcesDirectory)/Claranet-IT/templates
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory)/resources/templates'
              CleanTargetFolder: false
          
          - task: CopyFiles@2
            displayName: 'Task | Copy script files '
            inputs:
              SourceFolder: $(build.sourcesDirectory)/Claranet-IT/scripts
              Contents: '**'
              TargetFolder: '$(System.ArtifactsDirectory)/resources/scripts'
              CleanTargetFolder: false

          - publish: '$(build.artifactstagingdirectory)/resources'
            displayName: Publishing CaV-1-resources
            artifact: CaV-1-resources

  - stage: detectstatedrift
    displayName: Stage A | Detect Terraform State Drift
    jobs:
      - template: templates/pipeline/job.assertTerraformStateDrift.yaml@claranet-it
        parameters:
          jobPrefix: 'A1'
          Environment: ${{ parameters.Environment }}
          NlcNumber: ${{ parameters.NlcNumber }}
          poolVmImage: ${{ parameters.vmImageName }}
          ServiceConnectionName: ${{ parameters.ServiceConnectionName }}
